# Generated by Django 5.0.2 on 2024-03-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("artist", models.CharField(max_length=255)),
                ("duration", models.FloatField()),
                ("last_play", models.DateTimeField()),
            ],
        ),
    ]
